@baseUrl = http://localhost:3000

### 1. MessagesController (GET - findAll)

# @name findAll

GET {{baseUrl}}/messages

### 2. MessagesController (GET - findOne)

# @name findOne

GET {{baseUrl}}/messages/1

### 3. MessagesController (POST - create)

# @name create

POST {{baseUrl}}/messages
Content-Type: application/json

{
  "author": "John Doe",
  "message": "This is a new message."
}

### 4. MessagesController (PUT - update)

# @name update

PUT {{baseUrl}}/messages/1
Content-Type: application/json

{
  "author": "Max Verstappen",
  "message": "This is an updated message."
}

### 5. MessagesController (PATCH - partialUpdate)

# @name partialUpdate

PATCH {{baseUrl}}/messages/1
Content-Type: application/json

{
  "message": "This is a new updated message."
}

### 6. MessagesController (DELETE - remove)

# @name remove

DELETE {{baseUrl}}/messages/1

### 7. MessagesController (GET - findAll with Query Params)

# @name findAllFiltered

GET {{baseUrl}}/messages?author=John%20Doe&limit=10

### 8. MessagesController (GET - findAll with just one filter)

# @name findAllByAuthor

GET {{baseUrl}}/messages?author=Max%20Verstappen